[dev]
port = 3000
ws_port = 3001

[meta]
title = "~/techulus"
description = "Thoughts, experiments and ideas."
og_image_url = "https://rustyink.cli.rs/images/og.png"
base_url = "https://techulus.xyz"

[site]
script_urls = []
style_urls = [
  'https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css',
  'https://cdn.jsdelivr.net/npm/prismjs@1.29.0/themes/prism-tomorrow.min.css',
]

[navigation]
links = [
  { label = "~/", url = "/" },
  { label = "Open-source", url = "https://github.com/arjunkomath" },
  { label = "Twitter", url = "https://twitter.com/arjunz" },
]

[data]
author = "Arjun Komath"
author_link = "https://twitter.com/arjunz"
