[dev]
port = 3000
ws_port = 3001

[meta]
title = "~/techulus"
description = "Thoughts, experiments and ideas."

[site]
script_urls = ['https://cdn.tailwindcss.com?plugins=typography']
style_urls = [
  'https://cdn.jsdelivr.net/npm/prismjs@1.29.0/themes/prism-tomorrow.min.css',
]

[navigation]
links = [
  { label = "~/", url = "/" },
  { label = "Open-source", url = "https://github.com/arjunkomath" },
]
